### ISSUE TITLE
Aliases/redirects for old links so that they aren't broken

### ISSUE THREAD

**Issue by edwardcwang** [freechipsproject/www.chisel-lang.org#27]
See freechipsproject/chisel-bootcamp#81

At the very least:
* 'Chisel Cheatsheet' -> https://chisel.eecs.berkeley.edu/documentation.html
* 'Chisel API' -> https://chisel.eecs.berkeley.edu/api/#package

**Comment by seldridge** [comment]
I may need to play with this some more as the `/api/#package` redirect works for me locally, but not after publishing. The Cheatsheet link works now.

**Comment by seldridge** [comment]
Fixed via #35 and #38.

Also fixes: https://chisel.eecs.berkeley.edu/doc/chisel-cheatsheet3.pdf
