### ISSUE TITLE
Deprecate https://chisel.eecs.berkeley.edu/

### ISSUE THREAD

**Issue by seldridge** [freechipsproject/www.chisel-lang.org#7]
1. Setup `www.chisel-lang.org` to work with this repo's GitHub pages site
2. Make `chisel.eecs.berkeley.edu` a redirect to `www.chisel-lang.org`
3. Ensure that both `chisel-lang.org` and `www.chisel-lang.org` work

**Comment by seldridge** [comment]
Conclusion from today's meeting was to add a redirect from `chisel.eecs.berkeley.edu` to `www.chisel-lang.org`. We'll then plan to leave up the old website pages (to keep links live for a while), but add a notice on the website stating that it's moved.

@chick: Would you be able to add the redirect?

**Comment by seldridge** [comment]
301 redirect added.

**Comment by schoeberl** [comment]
I have a link to the Chisel cheatsheet in by book which how leads to 404 :-(

https://chisel.eecs.berkeley.edu/doc/chisel-cheatsheet3.pdf <https://chisel.eecs.berkeley.edu/doc/chisel-cheatsheet3.pdf>

Is the cheatsheet somewhere in chisel-lang.org <http://chisel-lang.org/>? Could it stay on the same place?

Cheers,
Martin

**Comment by seldridge** [comment]
@schoeberl: Use the following link to always link to the latest version of the cheatsheet: 

- https://github.com/freechipsproject/chisel-cheatsheet/releases/latest/download/chisel_cheatsheet.pdf

I'll get the old links up with a fix for #27 so old (published!) versions will still work.

**Comment by schoeberl** [comment]
> On 24 Sep, 2019, at 18:26, Schuyler Eldridge <notifications@github.com> wrote:
> 
> @schoeberl <https://github.com/schoeberl>: Use the following link to always link to the latest version of the cheatsheet:
> 
> https://github.com/freechipsproject/chisel-cheatsheet/releases/latest/download/chisel_cheatsheet.pdf <https://github.com/freechipsproject/chisel-cheatsheet/releases/latest/download/chisel_cheatsheet.pdf>
I will update for the second edition. That is the risk when using links in a book,
they get stale so quickly. But three weeks was very quick ;-)

> I'll get the old links up with a fix for #27 <https://github.com/freechipsproject/www.chisel-lang.org/issues/27> so old (published!) versions will still work.
> 
> 

Great! Does this also preserve the direct link to the PDF, which I used:

https://www.chisel-lang.org/doc/chisel-cheatsheet3.pdf <https://www.chisel-lang.org/doc/chisel-cheatsheet3.pdf>

Cheers,
Martin
